### ISSUE TITLE
Authentication error on parallel queries when using scram-sha-256 authentication

### ISSUE THREAD

**Issue by marcbachmann** [porsager/postgres#123]
Hey there, I just tried to write some benchmarks and then found some issue with the `scram-sha-256` authentication.
When running multiple queries in parallel, it will throw an Authentication error.

To reproduce it, you can start two containers, one with md5 authentication, the other with scram-sha-256:
```bash
docker run -d --name postgres-md5 --rm -p 5432:5432 -e POSTGRES_PASSWORD=password postgres:13-alpine
docker run -d --name postgres-scram --rm -p 5433:5432 -e POSTGRES_PASSWORD=password -e POSTGRES_INITDB_ARGS="--auth-host=scram-sha-256 --auth-local=scram-sha-256" postgres:13-alpine
```

Then execute this script:
```js
async function start (port) {
  const sql = require('postgres')(`postgres://postgres:password@localhost:${port}/postgres`, {no_prepare: true})

  try {
    await Promise.all([sql`SELECT 1`, sql`SELECT 1`, sql`SELECT 1`])
  } finally {
    sql.end({timeout: 0})
  }
}

start(5432)
  .catch((err) => console.error('Error from instance with md5 authentication: ', err))

start(5433)
  .catch((err) => console.error('Error from instance with scram authentication: ', err))
```

This results in that error:
```
Error from instance with scram authentication: PostgresError: password authentication failed for user "postgres"
    at Object.ErrorResponse (/benchmark/node_modules/postgres/lib/backend.js:131:22)
    at Socket.data (/benchmark/node_modules/postgres/lib/connection.js:233:25)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:302:12)
    at readableAddChunk (_stream_readable.js:278:9)
    at Socket.Readable.push (_stream_readable.js:217:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  severity_local: 'FATAL',
  severity: 'FATAL',
  code: '28P01',
  file: 'auth.c',
  line: '331',
  routine: 'auth_failed'
}
```

And sometimes in this one:
```
Error from instance with scram authentication: Error: The server did not return the correct signature
    at Object.SASLFinal (/benchmark/node_modules/postgres/lib/frontend.js:133:16)
    at Object.auth (/benchmark/node_modules/postgres/lib/frontend.js:65:23)
    at /benchmark/node_modules/postgres/lib/connection.js:89:29
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'SASL_SIGNATURE_MISMATCH'
}
```

**Comment by marcbachmann** [comment]
Fixed with #145

**Comment by porsager** [comment]
Hi @marcbachmann .. Don't know why I've overlooked this issue, but cool that you found the fix for it 💪

**Comment by porsager** [comment]
Fix released in [v2.0.0-beta.3](https://github.com/porsager/postgres/releases/tag/v2.0.0-beta.3)

**Comment by marcbachmann** [comment]
no problem. I also just didn't look at the code because I didn't have too much time back then and thought it might be more complex. Other projects also still have issues using SCRAM as it's not the default authentication protocol 😞.
